spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRES_USER:postgres}
    password: ${$POSTGRES_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${port:8100}

